### ISSUE TITLE
Page broken if first headline is hidden

### ISSUE THREAD

**Issue by Sypwn** [mittelab/ifauthex-dokuwiki-plugin#8]
If the first headline on a page is hidden, the page layout breaks.

The following page:
```
<ifauth @restricted_group>
====== Hidden ======
Hidden content.
</ifauth>

====== Public ======
Not hidden content.
```
displays like this for users not in restricted_group:
![image](https://user-images.githubusercontent.com/9245957/105531282-15d54100-5cb7-11eb-9afd-f466d503250d.png)

Release 2020-07-29 "Hogfather"
Default `dokuwiki` template

**Comment by 5p4k** [comment]
So I've dug through this, and the problem occurs in the following scenario: the first header of the page is enclosed in a hidden `ifauth` block.

I will see if I can get this properly fixed or if I need a workaround. In the meanwhile, to prevent page breakage, **do not put the first header inside an `ifauth` block**. You can use any other formatting as long as it's not a header.

---

**Technical details:**

The reason is that when the header is processed by the parser and lexer, it calls `Doku_Handler.header`. Any header opens a new section, thus setting `Doku_Handler.status['section'] = true;`. When the parser reaches the second header, the second header sees that a section is open and issues a `section_close` instruction. It looks like this:
```json
[
	["document_start",[]],
		["plugin",["ifauthex",[1," admin"],1,"<ifauth admin>"]],
		["header",["Hidden",3,16]],
		/* This section is opened by the header above */
		["section_open",[3]],
			["p_open",[]],
				["plugin",["ifauthex",[3,"private"],3,"private"]],
				["cdata",[""]],
			["p_close",[]],
			["plugin",["ifauthex",[4,null],4,"<\/ifauth>"]],
		/* Above: </ifauthex>, below: section_close issued by the following header. */
		["section_close",[]], 
		["header",["Visible",3,51]],
		["section_open",[3]],
			["p_open",[]],
				["cdata",["public"]],
			["p_close",[]],
		["section_close",[]],
	["document_end",[]]
]
```

for the following page:
```
<ifauth admin>
==== Hidden ====
private
</ifauth>
==== Visible ====
public
```
At render time, the html renderer writes a `</div>` tag in place of the `section_close` command, but there is no section that has been opened, because that command was hidden. Essentially it's because `ifauth` can break the page hierarchy.
